services:
  # frontend service
  frontend:
    container_name: frontend
    build: ./gui
    # Expose the frontend service on port 5000
    ports:
      - "5000:5000"

  # User service
  user:
    container_name: user
    build: ./user
    # Specify internal network
    networks:
      - user
    # Wait for the user-db service to be healthy before starting the user service
    depends_on:
      user-db:
        condition: service_healthy

    # User service database
  user-db:
    container_name: user-db
    image: postgres:16.3-bookworm
    # Specify volume
    volumes:
      - user-db-data:/var/lib/postgresql/data
    # Specify internal network
    networks:
      user:
        aliases: [ "user-db" ]
    # Set environment variables
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: glowing-banana
      POSTGRES_DB: user_db
    # Check for correct startup
    healthcheck:
      test: "pg_isready -U 'root' -d 'user_db' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  # Define volumes to ensure data persistence of service databases
  user-db-data: {}

networks:
  # Define networks to be used internally
  user:
    internal: true
